version: "3"
services:
    php-fpm:
        build: install/php-fpm
        ports:
            - 9020:9000
        volumes:
            - ./code:/var/www/html/
            - ./install/php-fpm/php.ini:/usr/local/etc/php/php.ini
        # links:
        #     - db
    nginx:
        build: install/nginx
        ports:
            - 8000:80
        volumes:
            - ./code:/var/www/html/        
        links:
            - php-fpm
    # db:
    #     image: mysql:5.6
    #     ports:
    #         - 3308:3306
    #     restart: always
    #     environment:
    #         MYSQL_DATABASE: tomonews
    #         MYSQL_USER: tomonews
    #         MYSQL_PASSWORD: Nma-apl1
    #         MYSQL_ROOT_PASSWORD: Nma-apl1
    #         BIND-ADDRESS: 0.0.0.0
    #     volumes:
    #         - MysqlVolume:/var/lib/mysql
# volumes:
#   MysqlVolume:
