version: "3"
services:
    php-fpm:
        build: install/php-fpm
        ports:
            - 9020:9000
        volumes:
            - ./code:/var/www/html/
            - ./install/php-fpm/php.ini:/usr/local/etc/php/php.ini
        # links:
        #     - db
    nginx:
        build: install/nginx
        ports:
            - 8080:80
        volumes:
            - ./code:/var/www/html/        
        links:
            - php-fpm
